User.create!(name: "ユーザー１")
User.create!(name: "ユーザー２")
User.create!(name: "ユーザー３")

Post.create!(content: "今日も勉強頑張る！", user_id: 1)
Post.create!(content: "毎日PDCA報告する", user_id: 1)
Post.create!(content: "絶対フリーエンジニアになる！", user_id: 1)
Post.create!(content: "たまにはカフェで気分を変えて勉強", user_id: 1)
Post.create!(content: "プログラミング楽しい", user_id: 1)
Post.create!(content: "勤怠Aが完成したら美味しいもの食べに行く！", user_id: 2)
Post.create!(content: "疲れたからちょっと休憩", user_id: 2)
Post.create!(content: "勤怠Aちょっと難しいけどその分成長できる", user_id: 2)
Post.create!(content: "今年も残り２ヶ月半!", user_id: 2)
Post.create!(content: "フリーエンジニアになったら何しよう", user_id: 2)
Post.create!(content: "Railsちょっとずつ理解できてきた", user_id: 3)
Post.create!(content: "たまには息抜き", user_id: 3)
Post.create!(content: "いいから黙ってさっさとやる", user_id: 3)
Post.create!(content: "人工インターンの参画楽しみ", user_id: 3)
Post.create!(content: "頑張って良かった！未来の自分", user_id: 3) 
